export const ActionTypes = {
    SET_TEMPLATE: 'SET_TEMPLATE',
    SORT_BY_CATEGORY : "SORT_BY_CATEGORY",
    SORT_BY_ORDERNAME : "SORT_BY_ORDERNAME",
    SORT_BY_DATE : "SORT_BY_DATE",
    HEADER_VALUE : "HEADER_VALUE",


}